[env]
TERM = "xterm-256color"

[font]
size = 14.0
normal = { family = "FiraCode Nerd Font", style = "Regular" }

#[font.normal]
#family = "FiraCode Nerd Font"
#style = "Regular"

[window]
opacity = 0.98

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]
